require_relative 'types/klass_definition'
require_relative 'types/arguments'
require_relative 'types/argument'
require_relative 'types/method_signature'
require_relative 'types/constant'
require_relative 'types/module_definition'
require_relative 'types/module'
require_relative 'types/klass'
