require_relative 'xmi/argument'
require_relative 'xmi/association'  
require_relative 'xmi/attribute' 
require_relative 'xmi/diagram' 
require_relative 'xmi/klass'
require_relative 'xmi/method'
require_relative 'xmi/module'
